can_driver:
  gear_ratios: [13.5, 150, 150, 148, 33, 33]
  encoder_resolution: 16384
  can_interface: "COM4"  # or "can0" on Linux
  bitrate: 500000
  default_speed: 200  # Reduced from 500 to 200 RPM
  default_acc: 50    # Reduced from 150 to 50 RPM/s  
