can_driver:
  bitrate: 500000
  can_interface: COM4
  encoder_resolution: 16384
  gear_ratios:
  - 13.5
  - 150
  - 150
  - 66
  - 33
  - 33
  motors:
  - id: 0
    speed_rpm: 1
    acceleration: 50
    direction: CCW
    homing_offset: -99195
    home_direction: CCW
    home_speed: 30
    offset_speed: 100
    endstop_level: High
  - id: 1
    speed_rpm: 600
    acceleration: 50
    direction: CCW
    homing_offset: -236000
    home_direction: CCW
    home_speed: 60
    offset_speed: 100

    endstop_level: High
  - id: 2
    speed_rpm: 200
    acceleration: 50
    direction: CCW
    homing_offset: -238796
    home_direction: CCW
    home_speed: 60
    offset_speed: 100
    endstop_level: Low
  - id: 3
    speed_rpm: 200
    acceleration: 50
    direction: CCW
    homing_offset: 209212
    home_direction: CW
    home_speed: 90
    offset_speed: 100
    endstop_level: Low
  - id: 4
    speed_rpm: 500
    acceleration: 40
    direction: CW
    homing_offset: 116474
    home_direction: CW
    home_speed: 100
    offset_speed: 100
    endstop_level: Low
  - id: 5
    speed_rpm: 500
    acceleration: 40
    direction: CCW
    homing_offset: -208066
    home_direction: CCW
    home_speed: 100
    offset_speed: 300
    endstop_level: Low
joints:
  coupled_mode: true
  joint_definitions:
  - index: 0
    motor_id: 0
    type: single
  - index: 1
    motor_id: 1
    type: single
  - index: 2
    motor_id: 2
    type: single
  - index: 3
    motor_id: 3
    type: single
  - coupling: subtract
    index: 4
    motor_ids:
    - 4
    - 5
    type: differential
  - coupling: add
    index: 5
    motor_ids:
    - 4
    - 5
    type: differential
