# Gesture recognition configuration for finger teleoperation
model:
  path: backend/core/vision/detectors/gesture/gesture_classifier.joblib
  probability_threshold: 0.82
  smoothing_window: 7
  min_consensus: 5
  max_history: 21

# Each gesture maps a classifier label to a teleoperation event.
gestures:
  - label: rock_and_roll
    event: zero_all_joints
    hands_required: 1
    hold_frames: 8
    overlay: "Rock & Roll ➜ Zero"
  - label: thumbs_down
    event: teleop_pause
    hands_required: 2
    hold_frames: 8
    allowed_hands: [Left, Right]
    overlay: "Thumbs Down (Both) ➜ Pause"
  - label: thumbs_up
    event: teleop_resume
    hands_required: 2
    hold_frames: 8
    allowed_hands: [Left, Right]
    overlay: "Thumbs Up (Both) ➜ Resume"
