# core/drivers/base.py
from typing import Protocol, List, Dict, Any

class Driver(Protocol):
    def connect(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def home(self) -> None: ...
    def send_joint_targets(self, q: List[float], t_s: float) -> None: ...
    def get_feedback(self) -> Dict[str, Any]: ...
    def open_gripper(self, force: float = 50.0) -> None: ...
    def close_gripper(self, force: float = 50.0) -> None: ...
    def set_gripper_position(self, position: float, force: float = 50.0) -> None: ...
    def grasp_object(self, force: float = 100.0) -> None: ...
    def estop(self) -> None: ...
    def handle_limits(self, feedback: Dict[str, Any]) -> bool: ...
