# core/drivers/base.py
from typing import Protocol, List, Dict, Any

class Driver(Protocol):
    def connect(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def home(self) -> None: ...
    def send_joint_targets(self, q: List[float], t_s: float) -> None: ...
    def get_feedback(self) -> Dict[str, Any]: ...
    def open_gripper(self) -> None: ...
    def close_gripper(self) -> None: ...
    def set_gripper_position(self, position: float) -> None: ...
    def estop(self) -> None: ...
